"""
テストワークフローの基本形
1. チェックアウトステップ
- uses: actions/checkout@v4
リポジトリからソースコードを取得

2. 言語セットアップステップ
- uses: actions/setup-go@v5
  with:
    go-version: '1.22'

3. テストステップ
- run: go test go/excellent/*.go
"""

name: Test
on:
  pull_request:  # プルリクエストが作成されたら起動
    paths: ['go/**/*.go']  # Goのファイルの変更時のみ
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@4  # ステップ1: チェックアウト
      - uses: actions/setup-go@v5  # スッテプ2: 言語セットアップ
        with:
          go-version: '1.22'
      - run: go test go/excellent/*.go  # ステップ3: テストの実行